name: New tag

on:
  push:
    branches:
    - master # check build without release
  create:
    tags:
    - v* # both build and release

jobs:

  static:
    runs-on: ubuntu-latest
    name: prepare static data
    steps:
    - uses: actions/checkout@v3
    - id: curdate
      run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
    - name: Restore static
      id: restore-static
      uses: actions/cache@v3
      with:
        path: |
          static/dictionaries
          static/sentences
        key: static-${{ steps.curdate.outputs.date }}-${{ hashFiles('.ci/Makefile') }}
    - name: Generate static
      if: steps.restore-static.outputs.cache-hit != 'true'
      run: |
        sudo apt-get -y install --no-install-recommends python3-pip
        pip3 install nltk
        cd .ci
        make static/dictionaries
        make static/sentences
    - name: Cache static
      uses: actions/cache/save@v3
      with:
        path: |
          static/dictionaries
          static/sentences
        key: ${{ steps.restore-static.outputs.cache-primary-key }}

  build:
    runs-on: ubuntu-latest
    needs: [static]
    name: ${{ matrix.build_arch }}
    strategy:
      matrix:
        include:
          - {build_arch: win32}
          - {build_arch: win64}
          - {build_arch: darwin_amd64}
          - {build_arch: darwin_arm64}
          - {build_arch: linux_i386}
          - {build_arch: linux_amd64}
          - {build_arch: linux_arm64}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - run: sudo apt-get -y install --no-install-recommends cmake libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libdbus-1-dev
    - id: curdate
      run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: |
          static/dictionaries
          static/sentences
        key: static-${{ steps.curdate.outputs.date }}-${{ hashFiles('.ci/Makefile') }}
        restore-keys: |
          static-${{ steps.curdate.outputs.date }}-
          static-
        fail-on-cache-miss: true
    - run: echo "" > cmake/sign.sh # @TODO: hack for artifact signing
    - name: build
      env:
        ARCH_INSTALLS: ${{ matrix.build_arch }}
      run: bash build-release.sh
    - name: upload release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: fb2c_*.zip
